diff --git a/.codeclimate.yml b/.codeclimate.yml
index e69de29..e676d61 100644
--- a/.codeclimate.yml
+++ b/.codeclimate.yml
@@ -0,0 +1,24 @@
+---
+engines:
+  duplication:
+    enabled: false
+    config:
+      languages:
+      - php
+  fixme:
+    enabled: true
+  phpmd:
+    enabled: true
+ratings:
+  paths:
+  - "**.php"
+  - "**.yml"
+exclude_paths: []
