version: 2

requirements:
  signed_off_by:
    required: false

always_pending:
  title_regex: 'WIP'
  labels:
    - "Status: Work in Progress"

group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^(A|a)pproved|\+1'
  reset_on_push:
    enabled: true

groups:
  Reviewers:
    required: 1

    users:
      - jasonwynn10
      - Aericio

    conditions:
      branches:
        - master
        - API3

    author_approval:
      required: true

    reset_on_reopened:
      enabled: true
      
    github_reviews:
      enabled: true

    reject_value: -2
