language: php

php:
# - 7.1
 - 7.0.13
# - 5.6.28
branches:
 - master

before_script:
 - cd /home/travis/build/
 - pecl install channel://pecl.php.net/pthreads-3.1.6
 - pecl install channel://pecl.php.net/weakref-0.3.2
 - echo | pecl install channel://pecl.php.net/yaml-2.0.0
 - git clone --recursive --branch=master https://github.com/pmmp/PocketMine-MP.git
 - mkdir -p PocketMine-MP/plugins/MyPlot
 - cp -rf jasonwynn10/MyPlot/src PocketMine-MP/plugins/MyPlot
 - cp -rf jasonwynn10/MyPlot/resources PocketMine-MP/plugins/MyPlot
 - cp -rf jasonwynn10/MyPlot/plugin.yml PocketMine-MP/plugins/MyPlot
 - cp -rf jasonwynn10/MyPlot/LICENSE PocketMine-MP/plugins/MyPlot
 - cp -rf jasonwynn10/MyPlot/build.php PocketMine-MP/
 - ls
 - cd PocketMine-MP/plugins/
 - ls
 - wget -O DevTools.phar https://github.com/PocketMine/DevTools/releases/download/v1.11.0/DevTools_v1.11.0.phar
 - cd /home/travis/build/PocketMine-MP

script:
 - php build.php

deploy:
  provider: releases
  user: "jasonwynn10"
  password: "$password"
  file: "/home/travis/build/PocketMine-MP/plugins/DevTools/MyPlot.phar"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

notifications:
 email: false
