name: SkyBlockPE
main: MyPlot\MyPlot
version: 1.1.6
api:
- 3.0.0
- 3.0.0-ALPHA7
authors:
 - Wiez
 - Exxarion
 - jasonwynn10
description: "SkyBlock recoded for MCPE based on MyPlot"
load: STARTUP
softdepend:
- EconomyAPI
- PocketMoney
- EssentialsPE
- EconomyPlus
extensions:
- sqlite3
- mysqli
- yaml
permissions:
    island.command:
        default: op
        children:
            island.command.help:
                default: true
            island.command.claim:
                default: true
            island.command.info:
                default: true
            island.command.generate:
                default: op
            island.command.addhelper:
                default: true
            island.command.removehelper:
                default: true
            island.command.denyplayer:
                default: true
            island.command.undenyplayer:
                default: true
            island.command.auto:
                default: true
            island.command.clear:
                default: true
            island.command.dispose:
                default: true
            island.command.reset:
                default: true
            island.command.biome:
                default: true
            island.command.biomes:
                default: true
            island.command.home:
                default: true
            island.command.homes:
                default: true
            island.command.name:
                default: true
            island.command.give:
                default: true
            island.command.warp:
                default: true
            island.command.done:
                default: true
            island.command.middle:
                default: true
            island.command.list:
                default: true
    island.admin:
        default: op
        children:
            island.admin.clear:
                default: op
            island.admin.biome:
                default: op
            island.admin.biomes:
                defualt: op
            island.admin.dispose:
                default: op
            island.admin.reset:
                default: op
            island.admin.addhelper:
                default: op
            island.admin.removehelper:
                default: op
            island.admin.denyplayer:
                default: op
            island.admin.undenyplayer:
                default: op
            island.admin.bypassdeny:
                default: op
            island.admin.build:
                default: op
                children:
                    island.admin.build.plot:
                        default: op
                    island.admin.build.road:
                        default: op
            island.admin.name:
                default: op
            island.admin.warp:
                default: op
            island.admin.done:
                default: op
            island.admin.middle:
                default: true
            island.admin.list:
                default: op
    island.claimplots:
        default: op
        children:
            island.claimplots.2:
                default: true
            island.claimplots.unlimited:
                default: op
