name: MyPlot
main: MyPlot\MyPlot
version: 1.0
load: STARTUP
api: 1.0.0
author: Wies and Exxarion
description: Plot and protection plugin
permissions:
  myplot.command:
    description: Allows users to use myplot features
    default: true
